version: "3.9"
services:
  app:
    build: .
    command: uvicorn tondeuse.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./tondeuse:/code/tondeuse
      - ./dumps:/code/dumps
    ports:
      - "8000:8000"
